#version: "3.9"

services:
  # DB PostgreSQL
  postgres:
    image:
      postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api-magazine-luiza-agendamento
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d api-magazine-luiza-agendamento" ]
      interval: 5s
      timeout: 5s
      retries: 10
  # Image da aplicação
  app:
    build: .
    container_name: api-notificacao-agendamento
    depends_on:
      # Dependência do DB criada anteriormente
      - postgres
      #condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/api-magazine-luiza-agendamento
      SPRING_DATASOURCE_USERNAME: postgres

      SPRING_DATASOURCE_PASSWORD: postgres
      #SPRING_FLYWAY_SCHEMAS: magalu
    ports:
      - "9293:9293"

volumes: # Adicione esta seção!
  postgres_data:  # Declaração do volume