server:
  port: 9293
spring:
  # profiles:
  #  active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL} # jdbc:postgresql://localhost:5432/api-magazine-luiza-agendamento #${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME} #postgres #${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD} #postgres #${SPRING_DATASOURCE_PASSWORD}
jpa:
  open-in-view: false
  hibernate:
    ddl-auto: update
    show-sql: true
    format-sql: true
flyway:
  #create-schemas: true
  enabled: true
  locations:
    classpath: db/migration
  baseline-on-migrate: true
  #schemas: magalu
spring-doc:
  pathsToMatch:
    - /api/**/v1/**
swagger-ui:
  user-root-path: true